import React, { useState } from "react";
import { useAddUserMutation } from "../services/usersAPI";
import "./Form.css";

const Form = () => {
  const [addUser] = useAddUserMutation();

  const [formData, setFormData] = useState({ email: "", password: "" });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const payload = {
        createdAt: new Date().toISOString(),
        description: "This Data is generated by RTK Query",
        email: formData.email,
        password: btoa(formData.password),
      };

      if (formData.password.length >= 8) {
        await addUser(payload);
        setFormData({ email: "", password: "" });
        window.location.reload();
      }
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <form className="form">
      <input
        name="email"
        type="text"
        value={formData.email}
        onChange={handleChange}
        className="form-input"
        placeholder="Enter Email"
        autoComplete="off"
      />
      <input
        name="password"
        type="password"
        value={formData.password}
        onChange={handleChange}
        className="form-input"
        placeholder="Enter Password"
        autoComplete="off"
      />
      <button onClick={handleSubmit} type="submit" className="form-button">
        Submit
      </button>
    </form>
  );
};

export default Form;
